"""
Admin UI for the CTO Cockpit product's own "CTO Cockpit" tab in
streamlit_app.py - a live, self-updating diagram of the actual repo's
product boundaries (not a hand-drawn one-off), plus a placeholder for a
future live AWS-setup view.

"Live" here means: PRODUCT_PATHS below is a small, explicit, rarely-
touched map of which top-level repo paths belong to which product - NOT
automatic import-graph introspection (this repo has no diagramming/graph
library and one isn't worth adding just for this; an import graph also
risks surfacing accidental coupling instead of intended product
boundaries). Everything BELOW that top level is listed for real via
pathlib at render time, so the "one level deeper" drill-down is always
accurate for the common case (files added, removed, or moved within a
product) without ever touching this file - only a brand-new top-level
product or a repo reorg needs the map below edited by hand.
unclassified_top_level_paths() is the drift guard that keeps that "rarely
touched" promise honest: a pytest assertion fails the moment a new
top-level file/dir shows up unclassified, rather than it silently just
not appearing anywhere.

Follows the "product owns its own admin module" convention set by
jobfinder_admin.py / req2prod/admin_ui.py: data-building (pure,
filesystem-only, no network calls) is kept separate from SVG rendering
(pure, string-only) and both are separate from the Streamlit-facing
render function, matching req2prod_pr_flow.py's established split.
"""

from pathlib import Path

import streamlit as st

REPO_ROOT = Path(__file__).parent

PRODUCTS: list[str] = ["Job Finder", "Req2Prod", "CTO Cockpit"]

# Top-level repo path -> product name. Anything NOT listed here and NOT
# in SHARED_INFRA_PATHS or EXCLUDED_NOISE below is unclassified - see
# unclassified_top_level_paths().
PRODUCT_PATHS: dict[str, str] = {
    # Dispatcher-heavy (wires together every product's admin tab) but
    # Job-Finder-dominant by actual line count (job search flow, quotas,
    # resume upload) - a defensible judgment call either way, not hidden.
    "streamlit_app.py": "Job Finder",
    "auth.py": "Job Finder",
    "job_search.py": "Job Finder",
    "jobfinder_admin.py": "Job Finder",
    "notify.py": "Job Finder",
    "reporting.py": "Job Finder",
    "ai_viewer.py": "Job Finder",
    "config": "Job Finder",  # Job Finder's own CrewAI config - distinct from req2prod/config/
    "assets": "Job Finder",
    "req2prod": "Req2Prod",
    "req2prod_agent_backend_mode.py": "Req2Prod",
    "req2prod_agent_steps.py": "Req2Prod",
    "req2prod_deploy_mode.py": "Req2Prod",
    "req2prod_pr_flow.py": "Req2Prod",
    "cto_cockpit_admin.py": "CTO Cockpit",
}

SHARED_INFRA_PATHS: list[str] = [
    "infra",
    ".github/workflows",
    "tests",
    ".streamlit/config.toml",
    "requirements.txt",
    "pytest.ini",
]

EXCLUDED_NOISE: set[str] = {
    "venv",
    "__pycache__",
    ".pytest_cache",
    "data",
    "users",
    ".vscode",
    ".git",
    ".env",
    ".env.example",
    ".gitignore",
    "README.md",
    "LICENSE",
    "run_job_finder.command",
    ".claude",
}

PRODUCT_COLORS: dict[str, str] = {
    "Job Finder": "#8b5cf6",  # violet - matches primaryColor in .streamlit/config.toml
    "Req2Prod": "#22d3ee",  # cyan
    "CTO Cockpit": "#f59e0b",  # amber - also signals "not yet built" via dashed border
}


def _path_count_label(count: int) -> str:
    return f"{count} path" if count == 1 else f"{count} paths"


def unclassified_top_level_paths(repo_root: Path = REPO_ROOT) -> list[str]:
    """Real repo-root entries not accounted for by PRODUCT_PATHS,
    SHARED_INFRA_PATHS, or EXCLUDED_NOISE. Should always be empty -
    covered by a pytest assertion so a new top-level file/dir forces a
    deliberate classification decision instead of silently not
    appearing anywhere in the live diagram."""
    known = set(PRODUCT_PATHS) | {p.split("/")[0] for p in SHARED_INFRA_PATHS} | EXCLUDED_NOISE
    return sorted(entry.name for entry in repo_root.iterdir() if entry.name not in known)


_NOISE_CHILD_NAMES = {"__pycache__", ".pytest_cache"}


def _list_one_level_deeper(repo_root: Path, top_level_path: str) -> list[str]:
    """For a file entry: just itself. For a directory entry: its
    immediate children (files and subdirs, subdirs NOT walked further -
    "one level deeper" than the product itself, not a full recursive
    tree), skipping generated bytecode-cache dirs wherever they show up
    - EXCLUDED_NOISE only filters top-level entries, but __pycache__/
    appears nested inside req2prod/, tests/, etc. too and is never
    meaningful architecture. Missing paths return []."""
    full = repo_root / top_level_path
    if not full.exists():
        return []
    if full.is_file():
        return [top_level_path]
    return sorted(
        f"{top_level_path}/{child.name}{'/' if child.is_dir() else ''}"
        for child in full.iterdir()
        if child.name not in _NOISE_CHILD_NAMES
    )


def build_product_tree(repo_root: Path = REPO_ROOT) -> dict[str, list[str]]:
    """For each product, every real path one level deeper than its
    declared top-level ownership. This is what makes the drill-down
    genuinely live: add/remove/move a file inside an owned path and this
    reflects it on the very next render, no code change needed."""
    tree: dict[str, list[str]] = {product: [] for product in PRODUCTS}
    for top_level_path, product in PRODUCT_PATHS.items():
        tree[product].extend(_list_one_level_deeper(repo_root, top_level_path))
    return {product: sorted(paths) for product, paths in tree.items()}


def build_shared_infra_tree(repo_root: Path = REPO_ROOT) -> list[str]:
    paths: list[str] = []
    for top_level_path in SHARED_INFRA_PATHS:
        paths.extend(_list_one_level_deeper(repo_root, top_level_path))
    return sorted(paths)


def render_architecture_svg(products: list[str] = PRODUCTS, path_counts: dict[str, int] | None = None) -> str:
    """Level-1 diagram: one box per product (with its live path count,
    so even this stable top-level view visibly reflects real change) plus
    a shared foundation box below - the live equivalent of the earlier
    one-off hand-drawn chat diagram. Pure string-building, no Streamlit
    calls, same palette/pattern as req2prod_pr_flow.py's
    render_pr_flow_svg. Deliberately static in shape (box count/labels) -
    the real "live" data is the drill-down below, not this box layout;
    architecture boundaries should look stable, not churn every render."""
    path_counts = path_counts or {}
    box_w, box_h, gap, top = 200, 90, 40, 30
    n = len(products)
    width = n * box_w + (n - 1) * gap + 40
    foundation_top = top + box_h + 50
    foundation_h = 60
    height = foundation_top + foundation_h + 30

    parts = [
        f'<svg viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg" '
        f'font-family="Inter, sans-serif">',
        f'<rect x="0" y="0" width="{width}" height="{height}" fill="#0a0a0f"/>',
    ]

    x = 20
    for product in products:
        color = PRODUCT_COLORS.get(product, "#8b5cf6")
        not_built = product == "CTO Cockpit"
        dash = ' stroke-dasharray="6,4"' if not_built else ""
        parts.append(
            f'<rect x="{x}" y="{top}" width="{box_w}" height="{box_h}" rx="12" '
            f'fill="{color}" fill-opacity="0.14" stroke="{color}" stroke-width="2"{dash}/>'
        )
        count = path_counts.get(product)
        label = f"{product} ({_path_count_label(count)})" if count is not None else product
        parts.append(
            f'<text x="{x + box_w / 2}" y="{top + box_h / 2 - 4}" fill="#f1f5f9" '
            f'font-size="14" font-weight="700" text-anchor="middle">{label}</text>'
        )
        if not_built:
            parts.append(
                f'<text x="{x + box_w / 2}" y="{top + box_h / 2 + 16}" fill="{color}" '
                f'font-size="11" text-anchor="middle">not yet built</text>'
            )
        parts.append(
            f'<line x1="{x + box_w / 2}" y1="{top + box_h}" '
            f'x2="{x + box_w / 2}" y2="{foundation_top}" stroke="#94a3b8" stroke-width="2"/>'
        )
        x += box_w + gap

    parts.append(
        f'<rect x="20" y="{foundation_top}" width="{width - 40}" height="{foundation_h}" '
        f'rx="10" fill="#94a3b8" fill-opacity="0.10" stroke="#94a3b8" stroke-width="1.5"/>'
    )
    parts.append(
        f'<text x="{width / 2}" y="{foundation_top + foundation_h / 2 + 5}" fill="#94a3b8" '
        f'font-size="13" text-anchor="middle">Infra as code (shared foundation)</text>'
    )
    parts.append("</svg>")
    return "\n".join(parts)


def render_cto_cockpit_tab() -> None:
    """The "CTO Cockpit" admin tab: live level-1 architecture diagram, a
    level-2 drill-down per product via st.expander (native Streamlit
    widget, matching this app's existing convention rather than custom
    JS interactivity), and a placeholder "AWS Setup" section."""
    st.markdown("### 🏗️ Live system architecture")
    st.caption(
        "Generated from this file's PRODUCT_PATHS map plus a real "
        "directory listing at render time - always reflects the "
        "current repo. Only needs a manual edit here when a brand-new "
        "top-level product or file is added."
    )

    tree = build_product_tree()
    shared = build_shared_infra_tree()
    path_counts = {product: len(paths) for product, paths in tree.items()}

    st.markdown(render_architecture_svg(path_counts=path_counts), unsafe_allow_html=True)

    st.markdown("#### One level deeper")
    for product in PRODUCTS:
        paths = tree[product]
        with st.expander(f"{product} ({_path_count_label(len(paths))})"):
            st.code("\n".join(paths) if paths else "No files yet.", language="text")

    with st.expander(f"Shared / foundation ({_path_count_label(len(shared))})"):
        st.code("\n".join(shared) if shared else "No files yet.", language="text")

    unclassified = unclassified_top_level_paths()
    if unclassified:
        st.caption(
            "⚠️ Not shown in the diagram above - classify in "
            "cto_cockpit_admin.py's PRODUCT_PATHS/SHARED_INFRA_PATHS/"
            f"EXCLUDED_NOISE: {', '.join(unclassified)}"
        )

    st.divider()

    st.markdown("### ☁️ AWS setup")
    st.caption(
        "Placeholder - the real infrastructure is Terraform in the "
        "sibling crewai-infra repo (published as job-finder-infra on "
        "GitHub), not this checkout, so it isn't introspected here yet."
    )
    st.info(
        "Coming soon: a live view of the crewai-infra Terraform stack "
        "(Lightsail instance, firewall rules, Secrets Manager, IAM "
        "policies, budget alerts), drill-down included."
    )
